<?php

namespace Olayemiolaomo\CapitalsageElasticLog\Providers;

use Carbon\Laravel\ServiceProvider;
use Illuminate\Log\Events\MessageLogged;
use Illuminate\Support\Facades\Log;
use Olayemiolaomo\CapitalsageElasticLog\Logger;

class ElasticLoggingServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $logger = new Logger();

        $this->mergeConfigFrom(__DIR__.'/../config/elk-logger.php', 'elk-logger');
        $this->publishes([__DIR__.'/../config/elk-logger.php' => config_path('elk-logger.php'),'elk-logger-file']);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}